--liquibase formatted sql

--changeset db:1 endDelimiter:;
create TABLE "PARTICIPANT" (
    "ID" number(10) PRIMARY KEY AUTO_INCREMENT,
    "NAME" VARCHAR(50) NOT NULL,
    "ALIAS" VARCHAR(50) NOT NULL,
    "CREATION_DATE" DATETIME NULL,
    "LAST_MODIFICATION_DATE" DATETIME  NULL,
    "CREATED_BY" VARCHAR(50) NULL
);